import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function POST(request: Request) {
    try {
        const { messageId, originalZone, correctedZone } = await request.json();

        const supabase = await createClient();

        // Log the correction for AI model fine-tuning
        const { error } = await supabase
            .from('user_corrections')
            .insert({
                notification_id: messageId,
                original_zone: originalZone,
                corrected_zone: correctedZone,
                raw_text_snapshot: 'Snapshot generated by feedback layer', // In a real app, fetch text first
            });

        if (error) {
            console.error('[LEARNING_LAYER_ERROR]:', error.message);
        }

        return NextResponse.json({ success: true, message: 'Feedback synced to Learning Layer' });
    } catch (error) {
        return NextResponse.json({ success: false, error: 'Invalid payload' }, { status: 400 });
    }
}
